In [ ]:
파일 입출력

열기

open()

f = open("파일명", 'w')
f.write("데이터")
f.close

# 바이너리 파일 열기
f = open("파일명", 'rb')
data = f.read()
print(data)
f.close

읽기

read()
read(n)

readline()
readlines()

f = open("파일명", 'r')
print(f.read())
f.close



쓰기

In [ ]:
# 파일의 내용 읽기

# f = open('./1_9______/31_score_data.txt', 'r')
# f = open('./1_9______/31_score_data1.txt', 'r')
f = open('./1_9______/31_score_data2.txt', 'r')
score = []

score = f.read()
# score = f.read().split()
print(score)
f.close()

In [ ]:
# 파일의 내용 읽기

f = open('./1_9______/31_score_data.txt', 'r')
# f = open('./1_9______/31_score_data1.txt', 'r')
# f = open('./1_9______/31_score_data2.txt', 'r')
score = []

for line in f :
    score.append(line)

print(score)
f.close()

In [ ]:
# 파일의 내용 읽기

# './1_9______/31_score_data.txt' 파일을 읽기 모드로 열고, 파일 내용을 읽어서 출력합니다.
with open('./1_9______/31_score_data.txt', 'r') as f :
	print(f.read())

# './1_9______/happy_day.txt' 파일을 읽기 모드로 열고, 파일 내용을 읽어서 출력합니다.
with open('./1_9______/happy_day.txt', 'r') as f :
	print(f.read())


In [ ]:
# 파일의 내용 읽기

d_score = {}

with open('./1_9______/31_score_data2.txt', 'r') as f :
    for line in f :
        (key, value) = line.split()
        d_score[int(key)] = value

print(d_score)

for key, value in d_score.items() :
    print(key, value)

for num in d_score :
    print(num, d_score[num])



In [ ]:
# 파일의 내용 읽기

f1 = open('./1_9______/31_score_data2.txt', 'r')

print(f1.readlines())
f1.close()

f2 = open('./1_9______/31_score_data2.txt', 'r')

for line in f2.readlines() :
    line = line.strip()
    print(line)
f2.close()

In [ ]:
# 바이너리 파일의 읽기 쓰기

f = open('./1_9______/python.png', 'rb')
data = f.read()
f.close()

f1 = open('./1_9______/python2.png', 'wb')
f1.write(data)
f1.close()

In [ ]:
#[연습문제] "매수종목.txt" 파일을 만들고 아래와 같이 입력한다.
# 005930 삼성전자
# 005380 현대차
# 035420 NAVER

f = open('./1_9______/매수종목.txt', 'w', encoding = 'utf-8')
f.write('005930 삼성전자\n005380 현대차\n035420 NAVER')
f.close()


f = open('./1_9______/매수종목.txt', encoding = 'utf-8')
lines = f.readlines()
# ['005930 삼성전자\n', '005380 현대차\n', '035420 NAVER']

data = {}
for line in lines :
    line = line.strip() #\n제거
    k, v = line.split() #딕셔너리로 변환
    data[k] = v
    
print(data)
f.close()

In [ ]:
import numpy as np 

a = [1, 2, 3, 4, 5]
#numpy는 쉼표가 없다
b = np.array(a) # a리스트를 b에 numpy리스트로 만듬
c = np.array([1, 3, 5])
d = np.array([[1, 2, 3], [4, 5, 6]]) # 2차원

print(a)
print(b)
print(c)
print(d)

In [ ]:
import numpy as np

a=np.array([1,2,3,4,5])
b=np.array([1,3,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(a[2])
print(b[-1])
print(a[1:3])
print(c[0])
print(c[0,2])
print(c[0][2])
print('d[0]:',d[0])
print(d[0])
print(d[0,1])

In [ ]:
import numpy as np

n_arr=np.array([[0,1,2,3],[4,5,6,7]],dtype='int64')

print(n_arr)
print("type",type(n_arr))
print("dtype",n_arr.dtype)
print("ndim:",n_arr.ndim)
print("shape",n_arr.shape)
print("size",n_arr.size)
print("itemsize:",n_arr.itemsize)
print("nbytes",n_arr.nbytes)
print("data:",n_arr.data)
print("메모리 주소:",id(n_arr)

In [112]:
import numpy as np

a = [1, 2, 3, 4, 5]
b = np.array(a)
c = np.array([1, 3, 5])
d = np.array([[1,2,3],[4, 5, 6]])

print(a+[2]) #a리스트에 2추가
print(b+[2]) # b NumPy리스트에 각 2를 더함

print(a*2)
print(b*2)
print()
print(c) 
print(c*[2, 4, 6])# c NumPy리슽에 2, 4, 6을 곱합
print()
print(d)
print(d+2) # d nupy리스트에 2를 더함
print()
print(d * c)

[1, 2, 3, 4, 5, 2]
[3 4 5 6 7]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]

[1 3 5]
[ 2 12 30]

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]

[[ 1  6 15]
 [ 4 15 30]]


In [ ]:
a = np.array([1,2,3], dtype=int)
b = np.array([1,1,2,2,3,3], dtype=float)
c = np.array([0,1,1,0], dtype=bool)

print(a)
print(b)
print(c)

print(a.dtype)
print(b.dtype)
print(c.dtype)

In [111]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print("a+b:", a+b)
print("a+b", np.add(a,b))

print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(a**2)

a+b: [ 6  8 10 12]
a+b [ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7])
# shape이 다를 경우 연산이 되지 않는다.
print(a+b) #error 뜸



In [35]:
#numpy.arange([start], stop, step], dtype="")
a1 = np.arange(12)
print("a1 :", a1)
a2=a1.reshape(3,4)
print(a2)
a3=a1.reshape(6,-1)
print(a3)
a4 = np.arange(36,dtype=float).reshape(3,4,3)
print(a4)

a1 : [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]
  [ 9. 10. 11.]]

 [[12. 13. 14.]
  [15. 16. 17.]
  [18. 19. 20.]
  [21. 22. 23.]]

 [[24. 25. 26.]
  [27. 28. 29.]
  [30. 31. 32.]
  [33. 34. 35.]]]


In [46]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

np.multiply(a1,a2)
np.matmul(a1, a2)
print(a1)

c = a1.flatten() #데이터가 새로만들어짐
d = a2.ravel() #포인터(주소)를 유지한다.
print(c)
print(d)
a1[0] = 0
a2[0][0] = 0

print(c)

print(d)

[[1 2]
 [3 4]]
[1 2 3 4]
[5 6 7 8]
[1 2 3 4]
[0 6 7 8]


In [52]:
#1
a1 = np.arange(1, 13).reshape(2,-1)
print(a1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [53]:
#2
a2 = np.arange(1,31).reshape(3,-1)
print(a2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [55]:
#3
a3 = np.arange(1,31).reshape(6,-1)
print(a3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [59]:
a4 = a3.transpose() #행과열을 바꿈
print(a4)

[[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


In [67]:
a1 =np.array([1,2,3,4])
a2 =np.array([5,2,7,4])

a1 == a2

print(np.array_equal(a1,a2))
print(a1 >= a2)


False
[False  True False  True]


In [75]:
a = np.array([4,2,6,5,1,3,0])

print(np.sort(a))# veiw
print(a)

a.sort()#a의 자체를 정렬
print(a)

print(np.sort(a)[::-1])
print(a)

[0 1 2 3 4 5 6]
[4 2 6 5 1 3 0]
[0 1 2 3 4 5 6]
[6 5 4 3 2 1 0]
[0 1 2 3 4 5 6]


In [80]:
import numpy as np

s = np.arange(0, 6).reshape(3,2)
print(s)

[[0 1]
 [2 3]
 [4 5]]


In [157]:
k = np.arange(0, 16).reshape(4,4)
#print(k)

a = k.transpose()[1]
print(a) 
print()
a = k[:,1]
print(a)
print()
b = k[2][1:4]
print(b)

c = k[:2, :2]
print(c) 
d = k[1:3, 1:3]
print(d)
print()


[ 1  5  9 13]

[ 1  5  9 13]

[ 9 10 11]
[[0 1]
 [4 5]]
[[ 5  6]
 [ 9 10]]

[[12 13 14 15]]
